- name: configure / Add User
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: on_create
    generate_ssh_key: yes
    ssh_key_type: ecdsa
    ssh_key_file: authorized_keys
  with_items: "{{ users }}"

- name: configure / Upadte yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  async: 300
  poll: 10

- name: configure / Import EPEL Repository
  yum:
    name: epel-release
    state: latest
    update_cache: yes
